# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('county', models.CharField(max_length=128)),
                ('hundred', models.CharField(max_length=128)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=20)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_of_manor', models.CharField(max_length=128, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('url', models.CharField(max_length=256)),
                ('lord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Lord')),
                ('overlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='map.Lord')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Place')),
            ],
        ),
    ]
