# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='roads',
            field=models.ManyToManyField(related_name='_place_roads_+', to='map.Place'),
        ),
    ]
