# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='map.Place')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Place')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='road',
            unique_together=set([('start', 'end')]),
        ),
    ]
