# Generated by Django 2.2.3 on 2019-07-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_place_roads'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settlement',
            name='population_type',
            field=models.CharField(choices=[('B', 'Burgers'), ('P', 'Peasants'), ('L', 'Knights'), ('M', 'Monks')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
